ChapterVerseUI/Models/Stock.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ChapterVerseUI.Models
{
    [Table("Stocks")]
    public class Stock
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int Quantity { get; set; }
        public Book? Book { get; set; }
    }
}

ChapterVerseUI/Controllers/StockController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ChapterVerseUI.Controllers
{
    [Authorize(Roles=nameof(Roles.Admin))]
    public class StockController : Controller
    {
        private readonly IStockRepo _stockRepo;

        public StockController(IStockRepo stockRepo)
        {
            _stockRepo = stockRepo;
        }
        public async Task<IActionResult> Index(string sTerm = "")
        {
            var stocks = await _stockRepo.GetStocks(sTerm);
            return View(stocks);
        }

        public async Task<IActionResult> ManageStock(int bookId)
        {
            var existingStock = await _stockRepo.GetStockByBookId(bookId);
            var stock = new StockDTO
            {
                BookId = bookId,
                Quantity = existingStock != null ? existingStock.Quantity : 0
            };
            return View(stock);
        }

        [HttpPost]
        public async Task<IActionResult> ManageStock(StockDTO stock)
        {
            if (!ModelState.IsValid)
                return View(stock);
            try
            {
                await _stockRepo.ManageStock(stock);
                TempData["successMessage"] = "Stock is updated successfully";
            }
            catch(Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ChapterVerseUI/Views/Stock/Index.cshtml
@model IEnumerable<StockDisplayModel>
@{
    Layout = "_AdminLayout";
}

<h2 class="text-primary-emphasis">Stocks</h2>
<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
    <input type="text" name="sTerm" class="form-control w-25" placeholder="Search by book"/>
    <button type="submit" class="btn btn-primary">Find</button>
    <a asp-action="Index" asp-asp-controller="Stock" class="btn btn-primary">Clear</a>
</form>

<table class="table table-striped table-hover">
    <tr>
        <th>Book</th>
        <th>Stock</th>
        <th>Actions</th>
    </tr>
    @foreach(var items in Model)
    {
        <tr>
            <td>@items.BookName</td>
            <td>@items.Quantity</td>
            <td>
                <a asp-action="ManageStock" asp-asp-controller="Stock" asp-route-bookId="@items.BookId" class="btn btn-outline-info">Update Stock</a>
            </td>
        </tr>
    }
</table>

ChapterVerseUI/Views/Stock/ManageStock.cshtml
@model StockDTO
@{
    Layout = "_AdminLayout";
}

<h2>ManageStock</h2>
<form asp-action="ManageStock">
    <input type="hidden" asp-for="BookId" />

    <div class="my-2">
        <label>Quantity</label>
        <input type="number" class="form-control" asp-for="Quantity" />
        <span class="text-danger" asp-validation-for="Quantity"></span>
    </div>

    <div class="my-2">
        <button class="btn btn-info" type="submit">Update</button>
        <a class="btn btn-primary" asp-action="Index" asp-controller="Stock">Back</a>
    </div>
</form>